[package]
name = "quality"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
walkdir = "2.3.2"
regex = "1.5.4"
reqwest = { version = "0.11", features = ["blocking", "json"] }

